# PowerShell task runner — Windows equivalent of the Makefile.
# Usage:  .\tasks.ps1 <target> [args...]
#   e.g.  .\tasks.ps1 dev
#         .\tasks.ps1 revision "add users table"

param(
    [Parameter(Position = 0)]
    [string]$Target = "help",
    [Parameter(Position = 1, ValueFromRemainingArguments = $true)]
    [string[]]$Rest
)

switch ($Target) {
    "help" {
        @"
Targets:
  install       Install Python dependencies
  dev           Run uvicorn with --reload
  test          Run pytest
  lint          Run ruff check
  fmt           Run ruff format
  db-up         Start Postgres + Mongo via Docker Compose
  db-down       Stop the DB containers
  migrate       Apply Alembic migrations (upgrade head)
  revision <m>  Create a new autogenerated Alembic revision
  docker-up     Bring up the full stack
"@ | Write-Host
    }
    "install"      { pip install -r requirements.txt }
    "dev"          { uvicorn app.main:app --reload }
    "test"         { pytest }
    "lint"         { ruff check app tests }
    "fmt"          { ruff format app tests }
    "db-up"        { docker compose up -d postgres mongo }
    "db-down"      { docker compose down }
    "migrate"      { alembic upgrade head }
    "revision"     {
        if (-not $Rest) { Write-Host "Usage: .\tasks.ps1 revision <message>"; exit 1 }
        alembic revision --autogenerate -m ($Rest -join ' ')
    }
    "docker-up"    { docker compose up -d }
    default        { Write-Host "Unknown target: $Target"; exit 1 }
}
